service: notification-service

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}

# We need to link our resource here in the infrastructure
resources:
  Resources:
    # CloudFormation resource with the logical name of MailQueue
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

# The place where we define our custom keys to be used elsewhere
custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    # We can use logical name of our CloudFormation resource to
    # get the arn for our SQS instance via intrinsic function
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
